---
- name: Create libsodium install directory
  file:
    path: "{{ orion_libsodium_dir }}"
    state: directory
    owner: "{{ orion_user }}"
    group: "{{ orion_group }}"
  become: true

- name: Extract libsodium
  unarchive:
    src: "{{ libsodium_download_url }}"
    remote_src: true
    dest: "{{ orion_libsodium_dir }}"
    owner: "{{ orion_user }}"
    group: "{{ orion_group }}"
    mode: '0775'
    extra_opts:
      - --strip-components
      - '1'
  become: true

- name: Configure libsodium compilation
  command:
    chdir: "{{ orion_libsodium_dir }}"
    cmd: ./configure
  become: true
  become_user: "{{ orion_user }}"
  register: config_libsodium

- name: Build libsodium
  make:
    chdir: "{{ orion_libsodium_dir }}"
  become: true
  become_user: "{{ orion_user }}"
  when: config_libsodium is changed

- name: Install libsodium
  make:
    chdir: "{{ orion_libsodium_dir }}"
    target: install
  become: true
  when: config_libsodium is changed